[package]
name = "todo_md"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.44"
dirs = "6.0.0"
dotenvy = "0.15.7"
regex = "1.12.3"
similar = "2.7.0"
strsim = "0.11.1"
uuid = { version = "1.21.0", features = ["v4"] }
